
project_id = "vmztmhwrsyomkohkglcv"

[functions.search-emails]
verify_jwt = true

[functions.add-google-config]
verify_jwt = true

[functions.update-google-config]
verify_jwt = true

[functions.delete-google-config]
verify_jwt = true

[functions.add-access-token]
verify_jwt = true

[functions.delete-access-token]
verify_jwt = true

[functions.update-access-token]
verify_jwt = true

[functions.fetch-access-tokens]
verify_jwt = true

[functions.fetch-google-configs]
verify_jwt = true

[functions.google-auth-callback]
verify_jwt = false

[functions.generate-google-auth-url]
verify_jwt = false
