[build]
  base = "."
  command = "npm run build:netlify"
  publish = "frontend/dist"
  
[build.environment]
  NODE_VERSION = "18"

# Redirects for the frontend SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Handle API requests with an external service or serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 